# Generated by Django 5.1.15 on 2026-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_add_username_remove_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpermission',
            name='module',
            field=models.CharField(choices=[('ticketing', 'Ticketing'), ('snack', 'Snack'), ('payment', 'Pembayaran'), ('report', 'Laporan'), ('participant', 'Peserta')], max_length=20),
        ),
    ]
