# Generated by Django 5.1.15 on 2026-08-11 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_orderitem_ticket_ticket_number_between_0001_1000_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['ticket_number']},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['name'], 'verbose_name': 'Season / Jenis Tiket', 'verbose_name_plural': 'Season / Jenis Tiket'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='collection_status',
            field=models.CharField(choices=[('NOT_COLLECTED', 'Belum Diambil'), ('COLLECTED', 'Sudah Diambil')], default='NOT_COLLECTED', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.orderitem'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sales_channel',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Pembeli'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('PAID', 'Paid'), ('ISSUED', 'Issued'), ('USED', 'Used / Checked-in'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=4, unique=True, verbose_name='ID Tiket'),
        ),
    ]
