# Generated by Django 5.1.15 on 2026-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_tickettype_bundle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='bundle_price',
            field=models.DecimalField(decimal_places=0, help_text='Harga untuk pembelian kelipatan 2 tiket', max_digits=12, verbose_name='Harga 2 Tiket (Bundling)'),
        ),
    ]
