# Generated by Django 5.1.15 on 2026-08-17 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('ticketing', '0007_alter_tickettype_bundle_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='ticket_number_between_0001_1000',
        ),
        migrations.AddField(
            model_name='order',
            name='ga_purchase_sent',
            field=models.BooleanField(default=False, verbose_name='GA4 Purchase Sent'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('ticket_number__gte', '0001')), name='ticket_number_gte_0001'),
        ),
    ]
