# Generated by Django 5.1.15 on 2026-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_remove_ticket_ticket_number_between_0001_1000_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Judul Naskah')),
                ('synopsis', models.TextField(blank=True, verbose_name='Sinopsis')),
                ('cast', models.TextField(blank=True, verbose_name='Pemain / Cast')),
                ('director', models.CharField(default='R. Pujiono', max_length=150, verbose_name='Sutradara')),
                ('production_by', models.CharField(default='Teater Peace & Peace Forum', max_length=150, verbose_name='Production By')),
                ('poster', models.ImageField(blank=True, upload_to='posters/', verbose_name='Poster Naskah')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Naskah Pertunjukan',
                'verbose_name_plural': 'Naskah Pertunjukan',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='tickettype',
            name='show_time',
            field=models.CharField(blank=True, help_text='Contoh: 08.30 - 11.30', max_length=50, verbose_name='Waktu Pertunjukan'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='naskah_list',
            field=models.ManyToManyField(blank=True, related_name='ticket_types', to='ticketing.showscript', verbose_name='Naskah yang Ditampilkan'),
        ),
    ]
