# Generated by Django 5.1.15 on 2026-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_cash_cashless_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
